spring:
  profiles:
    active: development
  thymeleaf:
    cache: false
    prefix: classpath:/static/
  devtools:
    add-properties: true
    restart:
      enabled: true
server:
  port: 3000
  error:
    whitelabel:
      enabled: false
#  error:
#    path: /error
management:
  server:
    port: 3001
# used in local mode, ZK cluster already running and accessible on 2181
#server:
#  port: 1970
#management:
#  server:
#    port: 1971

logging:
  level:
    com.konsilix: DEBUG
    org.apache.zookeeper: ERROR
    web: WARN
    org.thymeleaf: WARN
    root: WARN
